CREATE DATABASE IF NOT EXISTS inscritos;
USE inscritos;

DROP TABLE IF EXISTS INSCRITOS, ANO_ACADEMICO, UNI, ZONA, CURSOS;

CREATE TABLE CURSOS(
  CursoId INT AUTO_INCREMENT,
  Nome VARCHAR(64),
  PRIMARY KEY(CursoId));
  
CREATE TABLE ZONA(
  ZonaId INT AUTO_INCREMENT,
  Nome VARCHAR(64) NOT NULL,
  Num_Ins INT,
  PRIMARY KEY(ZonaId));
  
CREATE TABLE UNI(
  Nome VARCHAR(64) NOT NULL,
  ZonaId INT NOT NULL,
  Num_Ins INT,
  PRIMARY KEY(Nome),
  FOREIGN KEY(ZonaId) REFERENCES ZONA(ZonaId));
  
CREATE TABLE ANO_ACADEMICO(
--  AcaId INT AUTO_INCREMENT,
  Ano YEAR NOT NULL,
  CursoId INT NOT NULL,
  Num_Ins INT,
--  PRIMARY KEY(AcaId),
  PRIMARY KEY(Ano,CursoId),
  FOREIGN KEY(CursoId) REFERENCES CURSOS(CursoId));
    
CREATE TABLE INSCRITOS(
  InsId INT AUTO_INCREMENT,
  Ano YEAR NOT NULL,
  Uni VARCHAR(64) NOT NULL,
  Tipo ENUM ("Publico","Privado"),
  Num_Ins INT NOT NULL,
  PRIMARY KEY(InsId),
  FOREIGN KEY(Uni) REFERENCES UNI(Nome),
  FOREIGN KEY(Ano) REFERENCES ANO_ACADEMICO(Ano));